server:
  port: 8091

spring:
  application:
    name: msvc-group-two
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sofka-ssr
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    producer:
      bootstrap-servers: localhost:9092

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka